### PR TITLE
Fixed project target from 3.5 Client Profile to full .NET 3.5

### PR DESCRIPTION
**Pull request by HEskandari**
This would fix the problem with compilation.

### CODE REVIEW

**Comment by oskarb** [comment]
"the problem" - but there is no build problem on master. Do you mean this is required for PR #3?

**Comment by HEskandari** [comment]
@oskarb The solution wouldn't build in VS2012. Happy to update it to VS2015 as well. It is also submitted as a part of PR #3 and it makes sense to be a separate pull request.

**Comment by HEskandari** [comment]
I'll close this one as it was already part of the other PR.

**Comment by oskarb** [comment]
I wouldn't have minded having this as a separate commit/merge - I think it's good to keep it separate from feature work. Is there a reason why we're not making this .Net 4.0?

**Comment by HEskandari** [comment]
@oskarb There's more to it to upgrade to .NET 4.0. I'll submit a separate PR for upgrading to the latest VS / .NET.

**Pull request closed without merging**
